#pragma once

enum ZOMBIE_STAT_CA {
	STINKIE_HP,
	STINKIE_ATTACK,
	STINKIE_ATTACKSPEED,
	STINKIE_RANGE,
	CHUCKER_HP,
	CHUCKER_ATTACK,
	CHUCKER_ATTACKSPEED,
	CHUCKER_RANGE,
	HOLY_BONE_HP,
	HOLY_BONE_HEAL,
	HOLY_BONE_ATTACK_SPEED,
	HOLY_BONE_RANGE
};